name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10
      
      - name: Assemble
        run: ./gradlew assemble

      - name: Publish Staging
        run: ./gradlew publish

      - name: Release and Publish to Maven Central
        run: ./gradlew jreleaserFullRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GITHUB_USERNAME: ${{ github.actor }}
          JRELEASER_GITHUB_EMAIL: ${{ github.actor }}@users.noreply.github.com
          JRELEASER_GPG_PASSPHRASE : ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY : ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PUBLIC_KEY : ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME : ${{ secrets.CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN : ${{ secrets.CENTRAL_TOKEN }}